services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8001:81"
    volumes:
      - "./docker/configs/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./api:/app-api"
    depends_on:
      - api

  client:
    image: client
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    ports:
      - '8000:5173'
    volumes:
      - "./client:/client"
    depends_on:
      - api

  api:
    image: api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    volumes:
      - "./api:/app-api"
    depends_on:
      - cache
      - rabbitmq
      - db

  api-message-handler:
    image: api
    command: bin/console messenger:consume async -vv
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./api:/app-api"
    depends_on:
      rabbitmq:
        condition: service_healthy

  db:
    image: postgres:17-bookworm
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 'system'
    volumes:
      - "dbdata:/var/lib/postgresql/data:rw"

  cache:
    image: valkey/valkey:8.1-alpine
    ports:
      - "16379:6379"

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=dev_password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmqdata:/var/lib/rabbitmq/"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    volumes:
      - "mail_data:/data"
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  dbdata:
  rabbitmqdata:
  mail_data: