nelmio_api_doc:
    documentation:
        servers:
            - url: http://127.0.0.1:8001
              description: API over HTTP
        info:
            title: Stock checker
            description: Checks for stock info using AlphaVantage API
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        paths:
            /api/login_check:
                post:
                    summary: 'Login user'
                    description: 'Login user to generate a JWT Token'
                    requestBody:
                        description: 'JSON payload to user login'
                        required: true
                        content:
                            application/json:
                                schema:
                                    properties:
                                        email:
                                            description: 'The user email'
                                            type: string
                                            format: email
                                        password:
                                            description: 'Define a password'
                                            type: string
                                            format: password
                                    type: object
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
